# Generated by Django 4.0.3 on 2022-04-13 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_rename_date_posted_listing_date_listed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='price',
            field=models.IntegerField(default=103),
            preserve_default=False,
        ),
    ]
