# Generated by Django 4.0.3 on 2022-04-14 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_listing_city_listing_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='city',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='listing',
            name='country',
            field=models.CharField(max_length=100),
        ),
    ]
