# Generated by Django 4.0.3 on 2022-04-15 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_alter_listing_city_alter_listing_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='facility_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
